### ISSUE TITLE
Add combat tag on login option

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/Finale#5]
Previously that feature lived in Humbug (I think?). I think it's better suited here than in our own CTP fork, because we haven't been maintaining that at all.

Should be toggleable via config

**Comment by Diet-Cola** [comment]
Is this needed since you need to /logout anyway otherwise youll be combat logged?

**Comment by Maxopoly** [comment]
Yes, we'd still want an option to have a longer timer on login (the way it was before) and it's nice as general feature.

**Comment by Maxopoly** [comment]
Adressed by https://github.com/CivClassic/Finale/pull/7
