### ISSUE TITLE
CPS limiter is buggy

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/Finale#9]
Triggers at way too low CPS, I can click a mob at like 3 CPS and easily get the 9 CPS cap to trigger repeatedly

@jayms

**Comment by Maxopoly** [comment]
Apparently only an issue in creative mode for some reason

**Comment by jayms** [comment]
@Maxopoly I have no idea what this thread is about so I think you tagged the wrong person.

**Comment by Maxopoly** [comment]
No, it's what we talked about yesterday regarding the CPS limiter, but its apparently not a real issue anyway, so nevermind
